### PR TITLE
Restore program letter intercept view

### PR DESCRIPTION
**Pull request by rhysyngsun**
### What are the relevant tickets?

N/A

### Description (What does it do?)

Restores the program letter intercept view which was unintentionally removed in https://github.com/mitodl/mit-open/commit/1f824920dad10b5caf27236dc0aaa5a68455e7ff

### How can this be tested?

Testing instructions from the original PR for this code should still be valid: https://github.com/mitodl/mit-open/pull/605

### CODE REVIEW

**Comment by shanbady** [comment]
@rhysyngsun looks like a test is failing. I think its just a matter of wrapping the relative url in the test with frontend_absolute_url

**Comment by rhysyngsun** [comment]
@shanbady should be fixed now

**Review by shanbady — APPROVED** [review]
looks good! 
Screenshot 2024-10-09 at 11 43 19 AM

**Comment by shanbady** [comment]
@ChristopherChudzicki once this lands you should be in a place to test program letters locally to re-enable [the test](https://github.com/mitodl/mit-open/blob/f7a3882f34cc6a6765fefdf43c9dfb7e487527b5/frontends/main/src/app-pages/ProgramLetterPage/%5Bid%5D/view/ProgramLetter.test.tsx#L20) in the nextjs branch

**Pull request merged**
