### PR TITLE
Refactor OPEN_DISCUSSIONS_ env vars to MITOPEN_

### PR DESCRIPTION
**Pull request by Ardiea**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable

#### What are the relevant tickets?
Closes https://github.com/mitodl/ol-infrastructure/issues/1657

#### What's this PR do?
Refactors environment variables to be named in accordance with changes in salt-ops and ol-inf.

### CODE REVIEW

**Comment by shaidar** [comment]
I may be wrong, but think we should remove all references to reddit.

**Comment by Ardiea** [comment]
> I may be wrong, but think we should remove all references to reddit.

I removed them from `app.json` but it wayyyy beyond me to rip out reddit refs from the actual application code and if I yank them from `open_discussions/settings.py` I will break a lot of other stuff, I think.

**Comment by collinpreston** [comment]
> > I may be wrong, but think we should remove all references to reddit.
> 
> I removed them from `app.json` but it wayyyy beyond me to rip out reddit refs from the actual application code and if I yank them from `open_discussions/settings.py` I will break a lot of other stuff, I think.

I got started on removing all of the Reddit stuff.  I can incorporate the changes you made on this PR.

**Comment by collinpreston** [comment]
Associated issue: https://github.com/mitodl/mit-open/issues/45

**Review by mbertrand — CHANGES_REQUESTED** [review]
A few things need to be run to clean up the CI failures:

```
docker compose run --rm watch yarn run fmt-fix
docker compose run --rm web bash

# then in the bash shell:
isort learning_resources/*.py
black learning_resources
```
and commit the changes.

Also needs a rebase to clear up a conflict with the main branch.

**Review by mbertrand — CHANGES_REQUESTED** [review]
Not actually used, but `.env.example` should also be updated.

**Review by collinpreston — APPROVED** [review]
This looks good to me and works when launching the application locally.  I would update the .env.example file so that it's easier for other developers to get up and running.  My .env is:
```
ENABLE_INFINITE_CORRIDOR=True
CELERY_TASK_ALWAYS_EAGER=True
DJANGO_LOG_LEVEL=INFO
LOG_LEVEL=info
MITOPEN_BASE_URL=http://od.odl.local:8063
MITOPEN_COOKIE_NAME=discussions
MITOPEN_COOKIE_DOMAIN=odl.local
MITOPEN_HOSTNAME=od.odl.local
MITOPEN_MAX_COMMENT_DEPTH=6
MITOPEN_JWT_SECRET=
MITOPEN_USE_S3=False
INDEXING_API_USERNAME=mitodl
MAILGUN_SENDER_DOMAIN=
MAILGUN_KEY=
MAILGUN_RECIPIENT_OVERRIDE=
STATUS_TOKEN=
OPENSEARCH_INDEX=discussions_local
OPENSEARCH_INDEXING_CHUNK_SIZE=100
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_STORAGE_BUCKET_NAME=
CLOUDFRONT_DIST=
SOCIAL_AUTH_MICROMASTERS_LOGIN_URL=
YOUTUBE_DEVELOPER_KEY=
TIKA_SERVER_ENDPOINT=http://tika:9998/
TIKA_CLIENT_ONLY=True
WEBPACK_ANALYZE=True

SOCIAL_AUTH_OL_OIDC_OIDC_ENDPOINT=
SOCIAL_AUTH_OL_OIDC_KEY=
SOCIAL_AUTH_OL_OIDC_SECRET=
AUTHORIZATION_URL=
ACCESS_TOKEN_URL=
USERINFO_URL=
```

**Comment by Ardiea** [comment]
> I would update the .env.example file so that it's easier for other developers to get up and running.

I honestly thought I had done that after Matt suggested it earlier. It must have gotten lost in my rebasing / fighting with CI.

**Pull request merged**
