### PR TITLE
Setup codespaces

### PR DESCRIPTION
**Pull request by shanbady**
### What are the relevant tickets?
Closes https://github.com/mitodl/mit-open/issues/1382

### Description (What does it do?)
This PR adds a Github Codespace configuration do  we can setup disposable live and shareable demo environments right from github. The idea is that we would will now have shareable environments for PRs which we can share with the design/product team for feedback and also be able to test any feature that requires a publicly accessible endpoint.

### How can this be tested?
The codespace configuration for projects is sourced from the main branch so in order to put this together (and test) I had to create a personal fork of mit-open with these changes on main.

1. On the top right of this PR click the green "code" button and go to the codespaces tab and launch a codespace
Screenshot 2024-08-20 at 3 51 02 PM
2. This should start provisioning a code space in a new tab (this takes a bit of time so grab a coffee). You will eventually see some output that indicates the script is waiting for migrations to finish before fetching some data
Screenshot 2024-08-20 at 4 08 53 PM
3. Once this completes, the codespace should automatically load up the readme and the "ports" tab will indicate that there are 3 ports exposed.
4. There is a know issue in codespaces with CORS unless the backend endpoint is set to public. To do this, go to the ports tab and set port "8063" to public. For this reason also - DEBUG is set to False for codespaces in django 
Screenshot 2024-08-20 at 4 15 51 PM
5. You should at this point be able to visit the port 8602 endpoint and load it up. If it doesn't load -  try again in 2 minutes. it is likely that the frontend is still building.
6. If you want data to be automatically fetched upon loading up the codespace, you can add relevant secrets such as the edx client secret and key to your codespace secrets under the [codespace config page](https://github.com/settings/codespaces)

### Additional Context
- There are integrations with jetbrains and [visual studio](https://docs.github.com/en/codespaces/developing-in-a-codespace/using-github-codespaces-in-visual-studio-code) which might be worth trying out
- Codespaces are provisioned under your own personal account - each developer gets 120 free hours every month which I think should be more than enough considering not every PR will require a codespace. Your persoinal github settings page has some options for default instance sizes etc (i set mine to the smallest instance sizes).
- You can add secrets and more environment variables on the [codespace settings](https://github.com/settings/codespaces) page
- You will have to manually set the api's port to public each time you launch a codespace (noted in instructions above) due to a known limitation with cors in codespaces. see:
  - https://github.com/orgs/community/discussions/22399
  - https://github.com/orgs/community/discussions/31316
  - https://github.com/orgs/community/discussions/15351

### CODE REVIEW

**Comment by shanbady** [comment]
pre-commit.ci run

**Review by mbertrand — COMMENTED** [review]
Looks good, didn't test everything out fully yet like adding secrets but got it running and displaying the home page.  Really cool.  One suggestion: Add a section to the README that includes most of the instructions for testing this PR.  Also, mention that you can halt the codespace instance by going to https://github.com/codespaces, clicking the elipsis next to the instance, and then clicking "Stop"

**Review by feoh — APPROVED** [review]

**Review by mbertrand — APPROVED** [review]
👍 , a README section for this would be helpful, detailing how to set this up and also which files should be modified when new env variables are required (ie codespaces.env, devcontainer.json for secret values)

**Review by mbertrand — APPROVED** [review]
👍

**Pull request merged**
