### PR TITLE
Update Select and Dropdown components

### PR DESCRIPTION
**Pull request by ChristopherChudzicki**
### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/4673

### Description (What does it do?)
This PR aligns our Select and Dropdown components with Figma designs.

### Screenshots (if appropriate):
Screenshot 2024-06-24 at 11 14 55 AM
Screenshot 2024-06-24 at 8 07 34 PM
Screenshot 2024-06-24 at 8 04 32 PM
Screenshot 2024-06-24 at 8 04 08 PM

### How can this be tested?
Try Select and Dropdown components throughout the app. For exmaple
- Dropdown: *button that opens a menu*
    - The usermenu dropdown in top-right corner (when logged in)
- Select: *Input field with choices from a menu*
    - The "Sort" select field on search page (and channel pages)
    - The select-based form fields on `/dashboard#profile` (education, format, time) 
    - The "Topics" autocomplete field on `/learningpaths/` (creation / editing menu)

Things to try:
1. The entire select field should be clickable.  (In contrast to RC, where the edges are not clickable.)
2. The select field chevron should flip when the dropdown is open 
3. The "Selected" and "hover" state colors should match Figma
    - simultaneous selected + hover might not be in Figma, but I verified with @steven-hatch 
4. Try keyboard navigation of select menu
5. Try the autocomplete select (in Learningpaths editing dialogue)—it's implementation was slightly different. 
6. View the associated storybook stories under the "Dropdowns" folder, http://localhost:6006/?path=/story/smoot-design-dropdowns-simpleselect--single-select

### CODE REVIEW

**Comment by ChristopherChudzicki** [comment]
@steven-hatch I realized this morning I forgot to implement the border and border radius specified in Figma.
- top border: none
- bottom/sides: 2px border + border radius 4px.

Figma:
Screenshot 2024-06-25 at 9 47 32 AM

**However:** The dropdown doesn't always open downwards, so the top isn't always adjacent to the input field. Downwards is the default, but if there isn't enough room, the dropdown will open above or on top of the field.

Screenshot 2024-06-25 at 9 45 53 AM
Screenshot 2024-06-25 at 9 45 59 AM
Screenshot 2024-06-25 at 9 46 07 AM

What are your thoughts?  
1. Style border uniformly, no border thickness
2. style border uniformly, 2px thickness
3. style top + bottom differently, even though dropdown might open upwards or on top of input.

(1) or (2) would be my preference (aesthetically).

**Review by shanbady — CHANGES_REQUESTED** [review]
looks great! some minor things i noticed.

There appears to be a tag bleeding issue in this interface. I dont think its an issue with your PR since I see it on rc as well but it would be nice to fix:
Screenshot 2024-06-25 at 10 29 18 AM

Another interface that seems to deviate a bit is the start date dropdown on learning resource cards:
Screenshot 2024-06-25 at 10 29 47 AM

Final thing I noted (but wasnt sure if it was intended to be captured/aligned in this PR) is the subscribe button and the user menu in the navbar which deviate a little in style.
Screenshot 2024-06-25 at 10 41 53 AM
Screenshot 2024-06-25 at 10 42 07 AM

**Comment by ChristopherChudzicki** [comment]
@shanbady Thanks for catching those! I will look into them. 

For the chips inside autocomplete, I noticed that, too, but decided not to handle it here since the PR was getting a little large. I just reated an issue for it: https://github.com/mitodl/hq/issues/4701

**Comment by ChristopherChudzicki** [comment]
@shanbady Ready for re-review. I decided against changing the follow/unfollow width: I agree it looks odd being narrow. It also looks a little odd to me when it is as wide as the button:

Screenshot 2024-06-25 at 11 17 08 AM

This feels like an issue specific to the channel pages, so I'll leave it for when a more thorough design review is done there.

**Review by shanbady — APPROVED** [review]
Looks good! LGTM

**Pull request merged**
