### PR TITLE
New default image for learning resources

### PR DESCRIPTION
**Pull request by jonkafton**
### Description (What does it do?)

Replaces the default image for learning resources with a new one.

Displays it in the learning resource drawer where no image is set on the resource.

### Screenshots (if appropriate):

image

### How can this be tested?

Find a resource that has no image and check that the default is displayed in its card, list and drawer components.

This one currently has no image:

/search/?q=No+Code+AI+and+Machine+Learning%3A+Building+Data+Science+Solutions
/search/?resource=14465

### CODE REVIEW

**Review by abeglova — CHANGES_REQUESTED** [review]
Idk if this is required for the launch ... 

Should the image be cropped differently in the cards/resource view?

The default crop goes through the people which looks odd

**Comment by abeglova** [comment]
If this is required for the launch and/or @steven-hatch thinks the crop looks ok i can change my review

**Comment by sovsey** [comment]
Not required for Monday's demo!

**Comment by jonkafton** [comment]
@steven-hatch I've experimented cropping the image to the 1.925 aspect ratio we use on Learning Resource cards and drawer - 600x311px.

This produces:

image

image

That works ok down to aspects of around 1.4, if we ever needed:

image

After which we're cropping into the students. May be ok at smaller sizes. Currently on the mobile card view it look like:

image

 Also, do we have a better quality image? This one looks a bit over compressed / pixelated.

**Comment by jonkafton** [comment]
Image now updated to new one matching the card and drawer aspect ratio. Now we have:

image

image

image

**Comment by steven-hatch** [comment]
Looks good to me, thank you for the iterations on this! UX approves

**Review by abeglova — APPROVED** [review]
lgtm

**Pull request merged**
