### PR TITLE
add a bullet about collecting demographics to PrivacyPage.tsx

### PR DESCRIPTION
**Pull request by pdpinch**
### What are the relevant tickets?

N/A

### Description (What does it do?)

I accidentally removed a bullet from the list "What personal information we collect"

The current copy for the privacy page is at https://docs.google.com/document/d/1jIZytUsHp4BB0eE5rTRWdEjj30w1kt4Z

### CODE REVIEW

**Comment by pdpinch** [comment]
more edits coming

**Comment by sovsey** [comment]
@pdpinch while you're in there, do you want to update the contact email in the PI section to `mitlearn-support@mit.edu`? (Right now it's `mitopen-support@mit.edu`)

**Comment by pdpinch** [comment]
> while you're in there, do you want to update the contact email in the PI section to mitlearn-support@mit.edu? (Right now it's mitopen-support@mit.edu)

As far as I know, the value of that email address is managed in a site setting somewhere else. It's a combination of

https://github.com/mitodl/mit-open/blob/c3d01c04964f86d3ac0533c595314f970c33865e/frontends/mit-open/src/pages/PrivacyPage/PrivacyPage.tsx#L166-L167

and 

https://github.com/mitodl/ol-infrastructure/blob/754d5a883c45953733cf09ff01b9e9a300a72f06/src/ol_infrastructure/applications/mitopen/Pulumi.applications.mitopen.Production.yaml#L44

**Comment by sovsey** [comment]
Thanks! I will include as part of https://github.com/mitodl/hq/issues/5024.

**Review by gumaerc — APPROVED** [review]
👍

**Pull request merged**
